In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Working with Numpy

### Why Use NumPy?
* In Python we have lists that serve the purpose of arrays, but they are slow to process.

* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

* Arrays are very frequently used in data science, where speed and resources are very important

### Why is NumPy Faster Than Lists?
* NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

* This behavior is called locality of reference in computer science.

* This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [1]:
import numpy as np

# check version
print(np.__version__)

1.26.3


#### Arrays

1. 0-D Arrays
    * 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
2. 1-D Arrays
   * An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

    * These are the most common and basic arrays.
3. 2-D Arrays
    * An array that has 1-D arrays as its elements is called a 2-D array.

    * These are often used to represent matrix or 2nd order tensors.
4. 3-D arrays
    * An array that has 2-D arrays (matrices) as its elements is called 3-D array.

    * These are often used to represent a 3rd order tensor.

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# 0- D arrays  Create a 0-D array with value 42
arr_0d = np.array(42)
print(arr_0d)

# 1 - D arrays Create a 1-D array containing the values 1,2,3,4,5
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

# 2- D arrays Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

# 3- D arrays Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr_3d)



42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [2]:
# check dimensions the arrays
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


* Array Indexing

In [3]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [10]:
x = np.arange(10)
print(x)

for i in x:
    print(f'this is x[{i}] eliment: ',i)

print ( 'Acceing array from the end of array')

for i in x:
    print(f'this is x[- {i}] eliment: ',x[-i])

# Updating Array 
print(x)
x[4]= 34
print(x)

[0 1 2 3 4 5 6 7 8 9]
this is x[0] eliment:  0
this is x[1] eliment:  1
this is x[2] eliment:  2
this is x[3] eliment:  3
this is x[4] eliment:  4
this is x[5] eliment:  5
this is x[6] eliment:  6
this is x[7] eliment:  7
this is x[8] eliment:  8
this is x[9] eliment:  9
Acceing array from the end of array
this is x[- 0] eliment:  0
this is x[- 1] eliment:  9
this is x[- 2] eliment:  8
this is x[- 3] eliment:  7
this is x[- 4] eliment:  6
this is x[- 5] eliment:  5
this is x[- 6] eliment:  4
this is x[- 7] eliment:  3
this is x[- 8] eliment:  2
this is x[- 9] eliment:  1
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 34  5  6  7  8  9]


In [21]:
print (x.shape)
# changing the shape of array 
x.shape= (2,5) #changing rows and columns  to 2 and 5 respectively
print ("New Shape: ", x.shape) # now x is 2-dimensional with 2 rows and 5 columns
print(x)

# Accessing  elements in an array
print('seccond row, 4th column value:',x[1,3]) # answer should be 8
x[0][2] # accessing element at first row , third column which 2 , another way to accessing the array

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

(2, 5)
New Shape:  (2, 5)
[[ 0  1  2  3 34]
 [ 5  6  7  8  9]]
seccond row, 4th column value: 8
2nd element on 1st row:  2


In [22]:
# Access the third element of the second array of the first array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


**Example Explained**

arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]] and [[7, 8, 9], [10, 11, 12]]

Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

In [23]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


**Slicing Arrays**
<hr>
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [28]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[0:5])
print(arr[1:5:2])
print(arr[4:])
print(arr[:4])  # Slice elements from the beginning to index 4 (not included)

print('Negetive Slicing')
print(arr[-3:-1])




[2 3 4 5]
[1 2 3 4 5]
[2 4]
[5 6 7]
[1 2 3 4]
Negetive Slicing
[5 6]


* Slicing 2-D Arrays

In [33]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

print(arr[0:2, 2]) #  0:2 selecting rows, 2 selecting column

print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


**Explain seccond method**

[0:2, 2]: This part is the slicing notation used to specify which elements of the array we want to access. It consists of two slices separated by a comma:

0:2: This slice specifies the range of rows we want to select. It starts at index 0 and ends at index 2 (exclusive), meaning it includes rows with indices 0 and 1 (but not 2).

,: The comma separates the row slice from the column slice.

2: This slice specifies the column we want to select. It selects the column with index 2.

Therefore, arr[0:2, 2] selects elements from rows 0 to 1 and column 2 of the array arr.