In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Working with Numpy

### Why Use NumPy?
* In Python we have lists that serve the purpose of arrays, but they are slow to process.

* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

* Arrays are very frequently used in data science, where speed and resources are very important

### Why is NumPy Faster Than Lists?
* NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

* This behavior is called locality of reference in computer science.

* This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [3]:
import numpy as np

# check version
print(np.__version__)

1.26.3


#### Arrays

1. 0-D Arrays
    * 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
2. 1-D Arrays
   * An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

    * These are the most common and basic arrays.
3. 2-D Arrays
    * An array that has 1-D arrays as its elements is called a 2-D array.

    * These are often used to represent matrix or 2nd order tensors.
4. 3-D arrays
    * An array that has 2-D arrays (matrices) as its elements is called 3-D array.

    * These are often used to represent a 3rd order tensor.

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# 0- D arrays  Create a 0-D array with value 42
arr_0d = np.array(42)
print(arr_0d)

# 1 - D arrays Create a 1-D array containing the values 1,2,3,4,5
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

# 2- D arrays Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

# 3- D arrays Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr_3d)



42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
